name: Generate and Push Database

on:
  workflow_dispatch:

jobs:
  generate-db:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    permissions:
      contents: write

    steps:
      - name: Timeout
        run: sleep 10

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Restore cached database
        id: cache-db
        uses: actions/cache/restore@v5
        with:
            key: ${{ github.workflow }}
            path: |
                ./data/example.db
                
      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run Python script
        run: python main.py
      
      - name: Cache Database
        uses: actions/cache/save@v5
        with:
            key: ${{ github.workflow }}
            path: |
                ./data/example.db
